### ISSUE TITLE
Create VT struct feature should consider and rename mangled function name

### ISSUE THREAD

**Issue by tacbliw** [KasperskyLab/hrtng#8]
The "Add VT struct" function can create VT struct with C++ mangled name which looks very ugly. 

Consider a vtable like this:

```
.data.rel.ro:00575A80 ; `vtable for'NaviCoreController
.data.rel.ro:00575A80 _ZTV18NaviCoreController DCD 0          ; DATA XREF: LOAD:000485BC↑o
.data.rel.ro:00575A80                                         ; NaviCoreController::~NaviCoreController()+18↑o ...
.data.rel.ro:00575A80                                         ; offset to this
.data.rel.ro:00575A84                 DCD _ZTI18NaviCoreController ; `typeinfo for'NaviCoreController
.data.rel.ro:00575A88                 DCD _ZN18NaviCoreControllerD2Ev ; NaviCoreController::~NaviCoreController()
.data.rel.ro:00575A8C                 DCD _ZN18NaviCoreControllerD0Ev ; NaviCoreController::~NaviCoreController()
.data.rel.ro:00575A90                 DCD _ZN18NaviCoreController10receiveMsgEiRN3utl12ThreadRawMsgE ; NaviCoreController::receiveMsg(int,utl::ThreadRawMsg &)
```

The feature create the vtable struct looks like this:

```
00000000 /// @0x575A88
00000000 struct /*VFT*/ _575A88_vtbl // sizeof=0xC
00000000 {
00000000     void (*_ZN18NaviCoreControllerD2Ev)(NaviCoreController *__hidden this); // 0x4649B8
00000004     void (*_ZN18NaviCoreControllerD0Ev)(NaviCoreController *__hidden this); // 0x464D28
00000008     _BYTE (*_ZN18NaviCoreController10receiveMsgEiRN3utl12ThreadRawMsgE)[]; // 0x473FC8
0000000C };
```

The last funtion is the `NaviCoreController::receiveMsg` function. I expect when calling the function it just show as:

```
obj->vtable->receiveMsg(a1);
```

instead of

```
obj->vtable->_ZN18NaviCoreController10receiveMsgEiRN3utl12ThreadRawMsgE(a1);
```

**Comment by srgblv** [comment]
Thanks for report.
Probably fixed in a4be1ab, please check

**Comment by tacbliw** [comment]
I've just build and test it. It seems like `get_short_name` is not the answer. Error:

```
[hrt] 473FC8: no type for VTBL member "NaviCoreController::receiveMsg(int,utl::ThreadRawMsg &)"
```

`get_short_name` gives `NaviCoreController::receiveMsg(int,utl::ThreadRawMsg &)`, which should be just `receiveMsg`.

**Comment by srgblv** [comment]
`no type for VTBL member` is just a warning about the func has no typeinfo defined and vtbl member was created with  `void*` type. This situation usually fixed later  by "renaming/retyping assistance" feature when you have reversed the func.

I'll strip stuff is enclosed in brackets, please wait

**Comment by tacbliw** [comment]
Oh my bad, it's just a warning. But the struct actually have no member, so I think it might fail if you add struct fields with those names. 

```
00000000 /// @0x575A88
00000000 struct /*VFT*/ __attribute__((packed)) _575A88_vtbl // sizeof=0x0
00000000 {
00000000 };
```

Since you mention stripping stuff inside the brackets, please note that the name can get much more complicated. Here is an example:

```
utl::Array<utl::Pair<uint,MobileDeviceInfo>,utl::Pair<uint,MobileDeviceInfo> const&>::copy(utl::Array<utl::Pair<uint,MobileDeviceInfo>,utl::Pair<uint,MobileDeviceInfo> const&> const&,uint)
```

for this case I think it's best to keep only `copy`. 

And there are cases with function destructors in the form of `MyType::~MyType()`.  The `~` character is also invalid as struct field name.

**Comment by tacbliw** [comment]
Yes, it starts from 0x0575A88 as you said. I use "Add VT struct" at 0x0575A88  to create the struct.

And yes, I agree that short names may cause conflict so if there is no quick solution it's ok to use the long mangled name.

I will close this case. Thanks for the time~!
